# Task - 1: Aggregate Rating Prediction using Linear Regression

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Dataset .csv')
df.head()

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   
3        6318506                    Ooma           162  Mandaluyong City   
4        6314302             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   
3      SM Megamall, Ortigas, Mandaluyong City   
4      SM Megamall, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                          Japanese  ...  Botswana Pula(P)               Yes   
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes   
3                   Japanese, Sushi  ...  Botswana Pula(P)                No   
4                  Japanese, Korean  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   
1                  No                No                   No           3   
2                  No                No                   No           4   
3                  No                No                   No           4   
4                  No                No                   No           4   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  
1               4.5    Dark Green   Excellent   591  
2               4.4         Green   Very Good   270  
3               4.9    Dark Green   Excellent   365  
4               4.8    Dark Green   Excellent   229  

[5 rows x 21 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Restaurant ID         9551 non-null   int64  
 1   Restaurant Name       9551 non-null   object 
 2   Country Code          9551 non-null   int64  
 3   City                  9551 non-null   object 
 4   Address               9551 non-null   object 
 5   Locality              9551 non-null   object 
 6   Locality Verbose      9551 non-null   object 
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object 
 10  Average Cost for two  9551 non-null   int64  
 11  Currency              9551 non-null   object 
 12  Has Table booking     9551 non-null   object 
 13  Has Online delivery   9551 non-null   object 
 14  Is delivering now     9551 non-null   object 
 15  Switch to order menu 

In [5]:
df.duplicated().sum()

0

In [6]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [7]:
df.dropna(inplace = True)

In [8]:
len(df['Country Code'].unique())

15

In [9]:
df['Aggregate rating'].unique()

array([4.8, 4.5, 4.4, 4.9, 4. , 4.2, 4.3, 3.6, 4.7, 3. , 3.8, 3.7, 3.2,
       3.1, 0. , 4.1, 3.3, 4.6, 3.9, 3.4, 3.5, 2.2, 2.9, 2.4, 2.6, 2.8,
       2.1, 2.7, 2.5, 1.8, 2. , 2.3, 1.9])

In [10]:
(df.groupby('Country Code')['Currency'].nunique() == 1).all()

True

In [46]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

df['Is delivering now'] = encoder.fit_transform(df['Is delivering now'])
df['Switch to order menu'] = encoder.fit_transform(df['Switch to order menu'])
df['Has Table booking'] = encoder.fit_transform(df['Has Table booking'])
df['Has Online delivery'] = encoder.fit_transform(df['Has Online delivery'])


In [49]:
df.head()

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   
3        6318506                    Ooma           162  Mandaluyong City   
4        6314302             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   
3      SM Megamall, Ortigas, Mandaluyong City   
4      SM Megamall, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   

                           Cuisines  Average Cost for two          Currency  \
0        French, Japanese, Desserts                  1100  Botswana Pula(P)   
1                          Japanese                  1200  Botswana Pula(P)   
2  Seafood, Asian, Filipino, Indian                  4000  Botswana Pula(P)   
3                   Japanese, Sushi                  1500  Botswana Pula(P)   
4                  Japanese, Korean                  1500  Botswana Pula(P)   

   Has Table booking  Has Online delivery  Price range  Aggregate rating  \
0                  1                    0            3               4.8   
1                  1                    0            3               4.5   
2                  1                    0            4               4.4   
3                  0                    0            4               4.9   
4                  1                    0            4               4.8   

  Rating color Rating text  Votes  
0   Dark Green   Excellent    314  
1   Dark Green   Excellent    591  
2        Green   Very Good    270  
3   Dark Green   Excellent    365  
4   Dark Green   Excellent    229

In [22]:
# df[df['Is delivering now'] == 1]
len(df[df['Is delivering now'] == 1])

34

In [24]:
df[df['Switch to order menu'] == 1]
len(df[df['Switch to order menu'] == 1])

0

In [48]:
### We are going to remove two columns from the dataset permanently since they are not necessary for our work ahead. 
### Is delivering now and Switch to order menu

df.drop(['Is delivering now', 'Switch to order menu'], axis = 1, inplace = True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Restaurant ID         9551 non-null   int64  
 1   Restaurant Name       9551 non-null   object 
 2   Country Code          9551 non-null   int64  
 3   City                  9551 non-null   object 
 4   Address               9551 non-null   object 
 5   Locality              9551 non-null   object 
 6   Locality Verbose      9551 non-null   object 
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object 
 10  Average Cost for two  9551 non-null   int64  
 11  Currency              9551 non-null   object 
 12  Has Table booking     9551 non-null   object 
 13  Has Online delivery   9551 non-null   object 
 14  Is delivering now     9551 non-null   object 
 15  Switch to order menu 

In [7]:
df.duplicated().sum()

0

In [9]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

df['Has Table booking'] = encoder.fit_transform(df['Has Table booking'])
df['Has Online delivery'] = encoder.fit_transform(df['Has Online delivery'])

In [7]:
dflr = df[['Has Table booking', 'Has Online delivery', 'Is delivering now', 'Switch to order menu', 'Price range', 'Aggregate rating', 'Rating color', 'Rating text', 'Votes']]

In [8]:
dflr.head()

Has Table booking Has Online delivery Is delivering now  \
0               Yes                  No                No   
1               Yes                  No                No   
2               Yes                  No                No   
3                No                  No                No   
4               Yes                  No                No   

  Switch to order menu  Price range  Aggregate rating Rating color  \
0                   No            3               4.8   Dark Green   
1                   No            3               4.5   Dark Green   
2                   No            4               4.4        Green   
3                   No            4               4.9   Dark Green   
4                   No            4               4.8   Dark Green   

  Rating text  Votes  
0   Excellent    314  
1   Excellent    591  
2   Very Good    270  
3   Excellent    365  
4   Excellent    229

In [9]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

dflr['Is delivering now'] = encoder.fit_transform(dflr['Is delivering now'])
dflr['Switch to order menu'] = encoder.fit_transform(dflr['Switch to order menu'])
dflr['Has Table booking'] = encoder.fit_transform(dflr['Has Table booking'])
dflr['Has Online delivery'] = encoder.fit_transform(dflr['Has Online delivery'])


C:\Users\Atharva\AppData\Local\Temp\ipykernel_760\2714532311.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflr['Is delivering now'] = encoder.fit_transform(dflr['Is delivering now'])
C:\Users\Atharva\AppData\Local\Temp\ipykernel_760\2714532311.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflr['Switch to order menu'] = encoder.fit_transform(dflr['Switch to order menu'])
C:\Users\Atharva\AppData\Local\Temp\ipykernel_760\2714532311.py:6: SettingWithCopyWarning: 
A value is trying to be set on a c

In [10]:
dflr.head()

Has Table booking  Has Online delivery  Is delivering now  \
0                  1                    0                  0   
1                  1                    0                  0   
2                  1                    0                  0   
3                  0                    0                  0   
4                  1                    0                  0   

   Switch to order menu  Price range  Aggregate rating Rating color  \
0                     0            3               4.8   Dark Green   
1                     0            3               4.5   Dark Green   
2                     0            4               4.4        Green   
3                     0            4               4.9   Dark Green   
4                     0            4               4.8   Dark Green   

  Rating text  Votes  
0   Excellent    314  
1   Excellent    591  
2   Very Good    270  
3   Excellent    365  
4   Excellent    229

In [11]:
len(dflr[dflr['Is delivering now'] == 1])

34

In [12]:
len(dflr[dflr['Switch to order menu'] == 1])

0

In [13]:
dflr.drop(['Is delivering now', 'Switch to order menu'], axis = 1, inplace = True)

C:\Users\Atharva\AppData\Local\Temp\ipykernel_760\1352063529.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflr.drop(['Is delivering now', 'Switch to order menu'], axis = 1, inplace = True)


In [14]:
dflr.head()

Has Table booking  Has Online delivery  Price range  Aggregate rating  \
0                  1                    0            3               4.8   
1                  1                    0            3               4.5   
2                  1                    0            4               4.4   
3                  0                    0            4               4.9   
4                  1                    0            4               4.8   

  Rating color Rating text  Votes  
0   Dark Green   Excellent    314  
1   Dark Green   Excellent    591  
2        Green   Very Good    270  
3   Dark Green   Excellent    365  
4   Dark Green   Excellent    229

In [15]:
dflr['Aggregate rating'].unique()

array([4.8, 4.5, 4.4, 4.9, 4. , 4.2, 4.3, 3.6, 4.7, 3. , 3.8, 3.7, 3.2,
       3.1, 0. , 4.1, 3.3, 4.6, 3.9, 3.4, 3.5, 2.2, 2.9, 2.4, 2.6, 2.8,
       2.1, 2.7, 2.5, 1.8, 2. , 2.3, 1.9])

In [16]:
dflr['Rating color'].unique()

array(['Dark Green', 'Green', 'Yellow', 'Orange', 'White', 'Red'],
      dtype=object)

In [17]:
dflr['Rating text'].unique()

array(['Excellent', 'Very Good', 'Good', 'Average', 'Not rated', 'Poor'],
      dtype=object)

In [18]:
(dflr.groupby('Aggregate rating')['Rating color'].nunique() == 1).all()

True

In [19]:
(dflr.groupby('Rating color')['Rating text'].nunique() == 1).all()

True

In [20]:
dflr = dflr[dflr['Rating color'] != 'White']

In [21]:
dflr['Aggregate rating'].unique()

array([4.8, 4.5, 4.4, 4.9, 4. , 4.2, 4.3, 3.6, 4.7, 3. , 3.8, 3.7, 3.2,
       3.1, 4.1, 3.3, 4.6, 3.9, 3.4, 3.5, 2.2, 2.9, 2.4, 2.6, 2.8, 2.1,
       2.7, 2.5, 1.8, 2. , 2.3, 1.9])

In [22]:
dflr['Rating color'].unique()

array(['Dark Green', 'Green', 'Yellow', 'Orange', 'Red'], dtype=object)

In [23]:
dflr['Rating text'].unique()

array(['Excellent', 'Very Good', 'Good', 'Average', 'Poor'], dtype=object)

In [24]:
dflr.shape

(7394, 7)

In [25]:
x = dflr.drop(columns = 'Aggregate rating')
y = dflr['Aggregate rating']

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [27]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [28]:
ohe = OneHotEncoder()
ohe.fit(x[['Has Table booking', 'Has Online delivery', 'Price range', 'Rating color', 'Rating text', 'Votes']])

OneHotEncoder()

In [29]:
column_trans = make_column_transformer((OneHotEncoder(categories = ohe.categories_), ['Has Table booking', 'Has Online delivery', 'Price range', 'Rating color', 'Rating text', 'Votes']), 
                                       remainder = 'passthrough')

In [30]:
lr = LinearRegression()

In [31]:
pipe = make_pipeline(column_trans, lr)

In [32]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array([0, 1]),
                                                                            array([0, 1]),
                                                                            array([1, 2, 3, 4], dtype=int64),
                                                                            array(['Dark Green', 'Green', 'Orange', 'Red', 'Yellow'], dtype=object),
                                                                            array(['Average', 'Excellent', 'Good', 'Poor', 'Very Good'], dtype=object),
                                                                            array([    4,     5,     6, ...,  7931,  9667, 10934], dtype=int64)]),
                                                  ['Has Table booking',
                                                   'Has Online delivery',
                                                   'Price range',
                                                   'Rating color',
                                                   'Rating text', 'Votes'])])),
                ('linearregression', LinearRegression())])

In [33]:
y_pred = pipe.predict(x_test)

In [34]:
r2_score(y_test, y_pred)

0.8652165438988837

In [35]:
scores = []
for i in range(1000):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = i)
    lr = LinearRegression()
    pipe = make_pipeline(column_trans, lr)
    pipe.fit(x_train, y_train)
    y_pred = pipe.predict(x_test)
    scores.append(r2_score(y_test, y_pred))

In [36]:
np.argmax(scores)

268

In [37]:
scores[np.argmax(scores)]

0.8789024394195932

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = np.argmax(scores))
lr = LinearRegression()
pipe = make_pipeline(column_trans, lr)
pipe.fit(x_train, y_train)
y_pred = pipe.predict(x_test)
r2_score(y_test, y_pred)

0.8789024394195932

In [41]:
pipe.predict(pd.DataFrame([[1, 1, 4, 'Dark Green', 'Excellent', 600]], columns = ['Has Table booking', 'Has Online delivery', 'Price range', 'Rating color', 'Rating text', 'Votes']))

array([4.72757199])

In [46]:
import pickle as pkl
pkl.dump(pipe, open('LinearRgressionRestaurant.pkl', 'wb'))